name: GGMMO_Essentials
version: 1.0
description: GGMMO_Essentials utility plugin for GGMMO servers
author: Intrepid249
authors: []
website: https://github.com/ggmmo/GGMMO_Plugins_Main

main: ggmmo.essentials.GGMMO_Essentials
database: false
depend: []

commands:
  nameBlock:
    description: Rename a block the player is holding
    usage: /<command> <ItemName>
    permission: ggmmo.essentials.rename
    permission-message: Insufficient permission
  SetPermissionGroup:
    description: Set the permission group for a specified player
    usage: /<command> <Player> [Group]

permissions:
  ggmmo.essentials.*:
    description: Give access to all GGMMO commands
    children:
      ggmmo.essentials.placeblock:
        description: Allow you to build / place blocks
        default: false
      ggmmo.essentials.rename:
        description: Allow you to rename a held item
        default: false