name: GGMMO_Economy
version: 1.0
description: Provides an economy system and database
author: Intrepid249
authors: []
website: https://github.com/ggmmo/GGMMO_Plugins_Main

main: ggmmo.economy.GGMMO_Economy
database: false
depend:
  - Vault

commands:
  ggmmoeconomy:
    usage: /<command>
    description: Issue the main command
  createaccount:
    usage: /<command>
    description: Create a player economy account
  balance:
    usage: /<command>
    description: Check your economy balance
  pay:
    usage: /<command> <player> <amount>
    description: Pay another player some money
  addBal:
    usage: /<command> <player> <amount>
    description: Add money to a player's account
  subBal:
    usage: /<command> <player> <amount>
    description: Subtract money from a player's bank account. Type "/subBal <player> all" to clear a player's bank account

permissions: