groups:
  Player:
    default: true
    permissions:
    inheritance:
    info:
      prefix: '[Player] '
      build: false
      suffix: ''
  Mod:
    default: false
    permissions:
    inheritance:
    info:
      prefix: '[Mod] '
      build: true
      suffix: ''
  Admin:
    default: false
    permissions:
      - ggmmo.essentials.nameblock
      - ggmmo.essentials.placeblock
      - ggmmo.essentials.breakblock
    inheritance:
      - Mod
    info:
      prefix: '[Admin] '
      build: true
      suffix: ''
Users:
  ff980a11-7feb-4aa6-a49e-111f8e704738:
    Group: Admin
  176f4ecb-8a9c-4150-93fc-66fbea8e81ae:
    Group: Admin