name: GGMMO_DiscordChat
version: 1.0
description: Plugin wrapper to allow discord chat integration with the minecraft server
author: Intrepid249
authors: []
website: https://github.com/ggmmo/GGMMO_Plugins_Main

main: ggmmo.discordchat.GGMMO_DiscordChat
database: false
depend: []

commands:

permissions: