name: AdminTeleport
version: 1.1
description: This plugin will handle many different teleporting funcitons such as initial spawns, warps, and portals.
author: The_Pale_One
authors:
  - Intrepid249
website: https://github.com/ggmmo/GGMMO_Plugins_Main

main: ggmmo.adminteleport.GGMMO_AdminTeleport

commands:
  setjoinspawn:
    usage: /<command>
    description: This will set the initial spawn point for player joining
  setwarp:
      usage: /<command> <name>
      description: Set a warp at the player with a name
  warp:
      usage: /<command> <name>
      description: Warp to a set location

permissions: